services:
  ado-mcp:
    build: .
    image: ado-mcp
    stdin_open: true
    tty: false
    environment:
      AZURE_DEVOPS_ORG: ${AZURE_DEVOPS_ORG}
      AUTH_METHOD: ${AUTH_METHOD:-pat}
      PERSONAL_ACCESS_TOKEN: ${PERSONAL_ACCESS_TOKEN}
